import type { Metadata } from "next";
import { PageShell } from "@/components/page-shell";
import { ScoutPanel } from "@/components/scout-panel";

export const metadata: Metadata = { title: "Scout AI", description: "Evidence-grounded deal intelligence that combines CRM activity with Churnaut website signals." };

export default function ScoutPage() { return <PageShell><section className="page-hero"><div className="page-hero-inner"><p className="eyebrow">SCOUT AI · DEAL INTELLIGENCE</p><h1 className="display">Your pipeline has<br />a <em>pulse.</em></h1><p className="lede">Scout looks beyond static deal fields to explain what changed, what is at risk, and which evidence deserves your rep&apos;s attention.</p></div></section>
  <section className="scout-story section-pad"><div><p className="eyebrow">THE ANALYST LAYER</p><h2 className="section-title">A deal score<br />with a <em>reason.</em></h2><p className="section-copy">Scout assembles CRM activity, deal timing and Churnaut website signals, then produces an evidence-grounded brief. The goal is not another opaque number. It is a concise explanation your team can challenge and use.</p></div><ScoutPanel /></section>
  <section className="section-pad content-grid"><div><p className="eyebrow">WHAT SCOUT READS</p><h2 className="section-title">The story beneath<br />the <em>fields.</em></h2></div><div className="feature-grid"><article className="feature-card"><span>01</span><h3>Activity history</h3><p>Recency and cadence across emails, calls, meetings and CRM activity.</p></article><article className="feature-card"><span>02</span><h3>Website intent</h3><p>Known visits to pricing, case studies, integrations and other meaningful pages.</p></article><article className="feature-card"><span>03</span><h3>Deal pressure</h3><p>Close-date realism, time in stage, follow-up gaps and other signs of drift.</p></article><article className="feature-card"><span>04</span><h3>Momentum changes</h3><p>New stakeholders, repeat visits and shifts that can turn a quiet deal into an active one.</p></article></div></section>
  <section className="section-pad wide-story"><div className="wide-story-grid"><div><p className="eyebrow eyebrow-light">EVIDENCE BEFORE ADVICE</p><h2 className="section-title">Scout should never invent the story.</h2><p className="section-copy">Each brief is designed to stay grounded in the signals available to Churnaut and your connected CRM. It highlights uncertainty where context is missing rather than presenting a guess as fact.</p></div><div className="fact-list"><div className="fact"><span>01</span><div><h3>Pressure score</h3><p>A prioritized view of healthy, warning and at-risk deals.</p></div></div><div className="fact"><span>02</span><div><h3>Evidence trail</h3><p>The activities and visits that support the assessment.</p></div></div><div className="fact"><span>03</span><div><h3>Next-move context</h3><p>A practical suggestion tied to what actually changed.</p></div></div></div></div></section></PageShell>; }
