import type { Metadata } from "next";
import { PageShell } from "@/components/page-shell";
import { ProductWindow } from "@/components/product-window";

export const metadata: Metadata = { title: "Product", description: "See how Churnaut connects tracked links, deterministic visitor context, website personalization and sales action." };

export default function ProductPage() {
  return <PageShell><section className="page-hero"><div className="page-hero-inner"><p className="eyebrow">THE SIGNAL SYSTEM</p><h1 className="display">Your CRM knows who they are.<br />Your website should <em>too.</em></h1><p className="lede">Churnaut carries the context your rep earned in outbound all the way through the website visit—and turns that visit into something the team can act on.</p></div></section>
    <section className="section-pad content-grid"><div><p className="eyebrow">01 / THE MECHANISM</p><h2 className="section-title">Known before<br />they <em>arrive.</em></h2></div><div className="feature-grid"><article className="feature-card"><span>01</span><h3>Tracked links</h3><p>Create a link associated with a known session or CRM record and use it in the outreach you already send.</p></article><article className="feature-card"><span>02</span><h3>Deterministic resolve</h3><p>When the link opens, Churnaut resolves the known context instead of trying to infer identity from an IP address.</p></article><article className="feature-card"><span>03</span><h3>Live page swaps</h3><p>A lightweight snippet can change approved headlines, supporting copy, calls to action and calendar embeds using your routing rules.</p></article><article className="feature-card"><span>04</span><h3>Useful visit evidence</h3><p>See the person, company, page and visit timing—then connect that evidence back to the deal in your workflow.</p></article></div></section>
    <section className="section-pad wide-story"><div className="wide-story-grid"><div><p className="eyebrow eyebrow-light">FROM LINK TO LIVE PAGE</p><h2 className="section-title">Personalization without the probabilistic guessing game.</h2><p className="section-copy">Churnaut is deliberately narrow about identity. It works when there is a known signal—such as a tracked link—not when an anonymous visitor simply appears. That boundary makes the experience clearer for your team and more honest for the visitor.</p></div><div className="fact-list"><div className="fact"><span>01</span><div><h3>Set the rule</h3><p>Choose the signal, condition, page selector and approved content.</p></div></div><div className="fact"><span>02</span><div><h3>Install one snippet</h3><p>Load Churnaut after your page becomes interactive.</p></div></div><div className="fact"><span>03</span><div><h3>Resolve and apply</h3><p>The platform matches the known session, evaluates routing rules and returns the approved swaps.</p></div></div><div className="fact"><span>04</span><div><h3>Learn from the visit</h3><p>Visit signals become context for sales follow-up and Scout&apos;s deal analysis.</p></div></div></div></div></section>
    <section className="section-pad pricing-preview"><div className="split-heading"><div><p className="eyebrow">A VIEW OF THE PRODUCT</p><h2 className="section-title">The signal, made<br /><em>legible.</em></h2></div><p className="section-copy">A focused workspace for tracked links, recent visitors, personalization rules and the deals those visits can change.</p></div><div style={{height: "520px", maxWidth: "1050px", margin: "0 auto"}}><ProductWindow /></div></section></PageShell>;
}
